name: scheduled-upload-crowdin

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@develop
    - name: Upload Localization to Crowdin by fastlane
      env:
        CROWDIN_KEY: ${{ secrets.CROWDIN_API }}
      run: cd src && fastlane crowdin_upload
